### ISSUE TITLE
File sharing request

### ISSUE THREAD

**Issue by hiroki1953** [ldzhangyx/MusicMagus#3]
Hello, I'm Hiroki Kamada.   
I found this research very interesting and would like to study it further.   
I cloned this model to my local environment and tried to run it according to the instructions in the readme.   
However, when I ran `inference.ipynb`, the following error occurred:    
lpmc/music_captioning/exp/transfer/lp_music_caps/transfer.pth   
Could you please share this file?

**Comment by ldzhangyx** [comment]
Hi Hiroki,

This ckpt is a part of `LP-MusicCaps` repo. You can find the files from:

https://huggingface.co/seungheondoh/lp-music-caps/tree/main
