### ISSUE TITLE
there is no transfer.pth file error

### ISSUE THREAD

**Issue by Vaibhav99mishra** [ldzhangyx/MusicMagus#5]
as mentioned on readme i tried to ran the steps but getting this error

please help me out as i am trying to understand this project.

![image](https://github.com/user-attachments/assets/359e10df-bbc7-40df-b894-fc36c8d5954d)

**Comment by ldzhangyx** [comment]
Please download transfer.pth from the website below and place it to lpmc/music_captioning/exp/transfer/lp_music_caps/ folder.

https://huggingface.co/seungheondoh/lp-music-caps/blob/main/transfer.pth
