### ISSUE TITLE
KeyError: 'cache_position'

### ISSUE THREAD

**Issue by YiYang-SCUT** [ldzhangyx/MusicMagus#7]
<img width="866" alt="image" src="https://github.com/user-attachments/assets/b16f863c-ae21-4de2-809f-bcab4e262825">
 
hello, I wanna know why this problem occur? Thanks!

**Comment by ldzhangyx** [comment]
Hello. It should be a Huggingface version issue.

You can refer to https://github.com/huggingface/transformers/issues/29426
