### ISSUE TITLE
Thanks for your outstanding work

### ISSUE THREAD

**Issue by YiYang-SCUT** [ldzhangyx/MusicMagus#8]
Thanks for your outstanding work!
Is your idea borrowed from the idea of pix2pix-zero?But I don't think I saw you cite or mention about pix2pix-zero in your paper?

**Comment by ldzhangyx** [comment]
Hi,

Thanks for your issue. That is true, I got inspiration from pix2pix-zero and I do have a citation to this paper:

<img width="435" alt="image" src="https://github.com/user-attachments/assets/86aed77d-b4bf-4451-9e13-41aa737ffd64">
