### ISSUE TITLE
How to use gpt-3.5-turbo-instruct model correctly?

### ISSUE THREAD

**Issue by YiYang-SCUT** [ldzhangyx/MusicMagus#9]
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/444eee39-9d6f-4c8e-aebe-23ef70a278f8">
Now it seems that I can't use the gpt-3.5-turbo-instruct model, I was fine with the gpt-3.5-turbo model, will it affect the results if I use gpt-3.5-turbo? If it will affect the results, what should I do to use the gpt-3.5-turbo-instruct model correctly？Thank you for your outstanding work!!!

**Comment by ldzhangyx** [comment]
Thanks. It does not affect the results, if you change the API param. 

The main reason is that it is just a way to generate various captions. It can be anything, including either gpt-3.5-turbo-instruct or gpt-3.5-turbo. Just make sure the API is correct.
